### ISSUE TITLE
接入api的对照翻译似乎失效了，请问能否接入chatgpt，deepseek或本地大模型等实现对照翻译？

### ISSUE THREAD

**Issue by zjuhyf** [NoEdgeAI/pdfdeal#56]
新版本更新后，原有的对照翻译方案似乎失效了，https://github.com/Menghuan1918/pdfdeal/issues/1

**Comment by Menghuan1918** [comment]
是对转换后的latex进行翻译吗？

**Comment by zjuhyf** [comment]
markdown文件

**Comment by Menghuan1918** [comment]
https://github.com/NoEdgeAI/Doc2XAPITranslate
